//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public int StudentID { get; set; }
        public int CourseID { get; set; }
        public string Grade { get; set; }
        public bool Completed { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Students Students { get; set; }
    }
}
